In [1]:
import pandas as pd
import numpy as np

In [55]:
df=pd.read_csv(r"D:\Dastaset\Dataset\ecommerce_customer_data_custom_ratios.csv\ecommerce_customer_data_custom_ratios.csv")

In [57]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0.0,Christine Hernandez,37,Male,0
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0.0,Christine Hernandez,37,Male,0
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0.0,Christine Hernandez,37,Male,0
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0.0,Christine Hernandez,37,Male,0
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0.0,James Grant,49,Female,1

In [71]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                250000 non-null  int64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
 13  year                   250000 non-null  int32
 14  month                  250000 non-null  int32
 15  week_day               250000 non-null  object
 16  hour                   250000 non-null  int32
dtypes: datetime64[ns](1), int32(3), int64(8), object(5)
memory usage: 29.6+ MB
None
        Customer ID                  Purchase Date  Product Price  \
count  250000.00000                         250000  250000.000000
mean    25004.03624  2021-11-06 23:31:24.372304384     254.659512
min         1.00000            2020-01-01 00:15:00      10.000000
25%     12497.75000  2020-12-02 19:33:23.249999872     132.000000
50%     25018.00000            2021-11-06 13:10:59     255.000000
75%     37506.00000  2022-10-11 03:42:32.750000128     377.000000
max     50000.00000            2023-09-15 12:24:08     500.000000
std     14428.27959                            NaN     141.568577

            Quantity  Total Purchase Amount   Customer Age        Returns  \
count  250000.000000          250000.000000  250000.000000  250000.000000
mean        2.998896            2725.370732      43.940528       0.403076
min         1.000000             100.000000      18.000000       0.000000
25%         2.000000            1477.000000      31.000000       0.000000
50%         3.000000            2724.000000      44.000000       0.000000
75%         4.000000            3974.000000      57.000000       1.000000
max         5.000000            5350.000000      70.000000       1.000000
std         1.414694            1442.933565      15.350246       0.490517

                 Age          Churn           year          month  \
count  250000.000000  250000.000000  250000.000000  250000.000000
mean       43.940528       0.199496    2021.377992       6.186388
min        18.000000       0.000000    2020.000000       1.000000
25%        31.000000       0.000000    2020.000000       3.000000
50%        44.000000       0.000000    2021.000000       6.000000
75%        57.000000       0.000000    2022.000000       9.000000
max        70.000000       1.000000    2023.000000      12.000000
std        15.350246       0.399622       1.077485       3.353738

                hour
count  250000.000000
mean       11.486784
min         0.000000
25%         6.000000
50%        11.000000
75%        17.000000
max        23.000000
std         6.915558

In [59]:
df.isnull().sum()/len(df)*100

Customer ID               0.0000
Purchase Date             0.0000
Product Category          0.0000
Product Price             0.0000
Quantity                  0.0000
Total Purchase Amount     0.0000
Payment Method            0.0000
Customer Age              0.0000
Returns                  19.0384
Customer Name             0.0000
Age                       0.0000
Gender                    0.0000
Churn                     0.0000
dtype: float64

In [61]:

df['Returns'].fillna(0,inplace =True)

C:\Users\yash1\AppData\Local\Temp\ipykernel_8076\846934250.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Returns'].fillna(0,inplace =True)

In [63]:
def return_vlue (values):
    values=str(values).split('.')[0]
    return int(values)
df['Returns'] = df['Returns'].apply(return_vlue)

In [65]:
# convert Purchase date to_datetime 

df['Purchase Date']=pd.to_datetime(df['Purchase Date'])


df['year']=df['Purchase Date'].dt.year

df['month']=df['Purchase Date'].dt.month

df['week_day']=df['Purchase Date'].dt.day_name()

df['hour']=df['Purchase Date'].dt.hour

In [67]:
df.head()

,Customer ID,Purchase Date,Product Category,Product Price,Quantity,Total Purchase Amount,Payment Method,Customer Age,Returns,Customer Name,Age,Gender,Churn,year,month,week_day,hour
0,46251,2020-09-08 09:38:32,Electronics,12,3,740,Credit Card,37,0,Christine Hernandez,37,Male,0,2020,9,Tuesday,9
1,46251,2022-03-05 12:56:35,Home,468,4,2739,PayPal,37,0,Christine Hernandez,37,Male,0,2022,3,Saturday,12
2,46251,2022-05-23 18:18:01,Home,288,2,3196,PayPal,37,0,Christine Hernandez,37,Male,0,2022,5,Monday,18
3,46251,2020-11-12 13:13:29,Clothing,196,1,3509,PayPal,37,0,Christine Hernandez,37,Male,0,2020,11,Thursday,13
4,13593,2020-11-27 17:55:11,Home,449,1,3452,Credit Card,49,0,James Grant,49,Female,1,2020,11,Friday,17

In [73]:
pip install psycopg2 sqlalchemy

Collecting psycopg2
  Downloading psycopg2-2.9.10-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: sqlalchemy in c:\users\yash1\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\yash1\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\yash1\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading psycopg2-2.9.10-cp312-cp312-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   - -------------------------------------- 0.0/1.2 MB ? eta -:--:--
   --- ------------------------------------ 0.1/1.2 MB 194.1 kB/s eta 0:00:06
   --- ------------------------------------ 0.1/1.2 MB 194.1 kB/s eta 0:00:06
   --- ------------------------------------ 0.1/1.2 MB 194.1 kB/s eta 0:00:06
   ---- ----------------------------------- 0.1/1.2 MB 236.4 kB/s eta 0:00:05
   ---- ----------------------------------- 0.1/1.2 MB 236.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ----- ---------------------------------- 0.2/1.2 MB 229.4 kB/s eta 0:00:05
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 180.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.2/1.2 MB 148.0 kB/s eta 0:00:07
   ------- -------------------------------- 0.2/1.2 MB 148.0 kB/s eta 0:00:07
   ------- -------------------------------- 0.2/1.2 MB 148.0 kB/s eta 0:00:07
   -------- ------------------------------- 0.3/1.2 MB 157.2 kB/s eta 0:00:06
   -------- ------------------------------- 0.3/1.2 MB 157.2 kB/s eta 0:00:06
   --------- ------------------------------ 0.3/1.2 MB 153.1 kB/s eta 0:00:06
   --------- ------------------------------ 0.3/1.2 MB 160.8 kB/s eta 0:00:06
   --------- ------------------------------ 0.3/1.2 MB 160.8 kB/s eta 0:00:06
   --------- ------------------------------ 0.3/1.2 MB 160.8 kB/s eta 0:00:06
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ----------- ---------------------------- 0.3/1.2 MB 178.7 kB/s eta 0:00:05
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------ --------------------------- 0.4/1.2 MB 146.1 kB/s eta 0:00:06
   ------------- -------------------------- 0.4/1.2 MB 128.3 kB/s eta 0:00:07
   ------------- -------------------------- 0.4/1.2 MB 128.3 kB/s eta 0:00:07
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   -------------- ------------------------- 0.4/1.2 MB 137.1 kB/s eta 0:00:06
   ---------------- ----------------------- 0.5/1.2 MB 134.6 kB/s eta 0:00:06
   ---------------- ----------------------- 0.5/1.2 MB 134.6 kB/s eta 0:00:06
   ---------------- ----------------------- 0.5/1.2 MB 134.6 kB/s eta 0:00:06
   ---------------- ----------------------- 0.5/1.2 MB 134.6 kB/s eta 0:00:06
   ---------------- ----------------------- 0.5/1.2 MB 134.6 kB/s eta 0:00:06
   ------------------ --------------------- 0.5/1.2 MB 139.8 kB/s eta 0:00:05
   ------------------ --------------------- 0.5/1.2 MB 139.8 kB/s eta 0:00:05
   ------------------ --------------------- 0.5/1.2 MB 139.8 kB/s eta 0:00:05
   ------------------ --------------------- 0.5/1.2 MB 139.8 kB/s eta 0:00:05
   -------------------- ------------------- 0.6/1.2 MB 145.1 kB/s eta 0:00:05
   -------------------- ------------------- 0.6/1.2 MB 145.9 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 150.4 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   --------------------- ------------------ 0.6/1.2 MB 153.7 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ----------------------- ---------------- 0.7/1.2 MB 151.9 kB/s eta 0:00:04
   ------------------------- -------------- 0.7/1.2 MB 148.9 kB/s eta 0:00:03
   -------------------------- ------------- 0.8/1.2 MB 150.4 kB/s eta 0:00:03
   -------------------------- ------------- 0.8/1.2 MB 150.4 kB/s eta 0:00:03
   -------------------------- ------------- 0.8/1.2 MB 150.8 kB/s eta 0:00:03
   -------------------------- ------------- 0.8/1.2 MB 150.8 kB/s eta 0:00:03
   -------------------------- ------------- 0.8/1.2 MB 150.8 kB/s eta 0:00:03
   --------------------------- ------------ 0.8/1.2 MB 152.6 kB/s eta 0:00:03
   --------------------------- ------------ 0.8/1.2 MB 152.6 kB/s eta 0:00:03
   --------------------------- ------------ 0.8/1.2 MB 152.6 kB/s eta 0:00:03
   --------------------------- ------------ 0.8/1.2 MB 152.6 kB/s eta 0:00:03
   --------------------------- ------------ 0.8/1.2 MB 152.6 kB/s eta 0:00:03
   ----------------------------- ---------- 0.9/1.2 MB 155.9 kB/s eta 0:00:02
   ----------------------------- ---------- 0.9/1.2 MB 155.9 kB/s eta 0:00:02
   ----------------------------- ---------- 0.9/1.2 MB 155.9 kB/s eta 0:00:02
   ----------------------------- ---------- 0.9/1.2 MB 155.9 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   ------------------------------ --------- 0.9/1.2 MB 156.1 kB/s eta 0:00:02
   --------------------------------- ------ 1.0/1.2 MB 122.0 kB/s eta 0:00:02
   --------------------------------- ------ 1.0/1.2 MB 122.0 kB/s eta 0:00:02
   ---------------------------------- ----- 1.0/1.2 MB 123.9 kB/s eta 0:00:02
   ---------------------------------- ----- 1.0/1.2 MB 123.9 kB/s eta 0:00:02
   ----------------------------------- ---- 1.0/1.2 MB 127.5 kB/s eta 0:00:01
   ----------------------------------- ---- 1.0/1.2 MB 127.5 kB/s eta 0:00:01
   ----------------------------------- ---- 1.0/1.2 MB 127.5 kB/s eta 0:00:01
   ----------------------------------- ---- 1.0/1.2 MB 127.5 kB/s eta 0:00:01
   ----------------------------------- ---- 1.0/1.2 MB 127.5 kB/s eta 0:00:01
   -------------------------------------- - 1.1/1.2 MB 131.6 kB/s eta 0:00:01
   -------------------------------------- - 1.1/1.2 MB 131.6 kB/s eta 0:00:01
   ---------------------------------------  1.1/1.2 MB 134.0 kB/s eta 0:00:01
   ---------------------------------------  1.2/1.2 MB 134.9 kB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 135.5 kB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.10
Note: you may need to restart the kernel to use updated packages.

In [75]:
# import data to Postgre sql 
from sqlalchemy import create_engine

engine=create_engine('postgresql://postgres:saurav120@localhost:5432/e-commerce')

df.to_sql('e-commerce', engine, if_exists='replace', index=False)

1000

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer ID            250000 non-null  int64
 1   Purchase Date          250000 non-null  datetime64[ns]
 2   Product Category       250000 non-null  object
 3   Product Price          250000 non-null  int64
 4   Quantity               250000 non-null  int64
 5   Total Purchase Amount  250000 non-null  int64
 6   Payment Method         250000 non-null  object
 7   Customer Age           250000 non-null  int64
 8   Returns                250000 non-null  int64
 9   Customer Name          250000 non-null  object
 10  Age                    250000 non-null  int64
 11  Gender                 250000 non-null  object
 12  Churn                  250000 non-null  int64
 13  year                   250000 non-null  int32
 14  month                  250000 non-null  int32
 15  week_day               250000 non-null  object
 16  hour                   250000 non-null  int32
dtypes: datetime64[ns](1), int32(3), int64(8), object(5)
memory usage: 29.6+ MB